package com.seventythreestrings.valuation.api.debtmodel.enums;

public enum DateType {
	ORIGINATION("Origination"),
	INTEREST("Interest"),
	REPAYMENT("Repayment"),
	DEALFEES("Deal Fees"),
	UNDRAWN_CAPITAL("Undrawn Capital"),
	SKIMS("Skims"),
	CUSTOMIZABLE("Customizable"),
	MATURITY("Maturity"),
	INTEREST_AND_REPAYMENT("Interest and Repayment"),
	INTEREST_AND_DEALFEES("Interest and Deal Fees"),
	INTEREST_AND_UNDRAWN_CAPITAL("Interest and Undrawn Capital"),
	INTEREST_AND_SKIMS("Interest and Skims"),
	INTEREST_AND_CUSTOMIZABLE("Interest and Customizable"),
	INTEREST_AND_MATURITY("Interest and Maturity"),
	REPAYMENT_AND_DEALFEES("Repayment and Deal Fees"),
	REPAYMENT_AND_UNDRAWN_CAPITAL("Repayment and Undrawn Capital"),
	REPAYMENT_AND_SKIMS("Repayment and Skims"),
	REPAYMENT_AND_CUSTOMIZABLE("Repayment and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL("Deal Fees and Undrawn Capital"),
	DEALFEES_AND_SKIMS("Deal Fees and Skims"),
	DEALFEES_AND_CUSTOMIZABLE("Deal Fees and Customizable"),
	DEALFEES_AND_MATURITY("Deal Fees and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS("Undrawn Capital and Skims"),
	UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Undrawn Capital and Customizable"),
	UNDRAWN_CAPITAL_AND_MATURITY("Undrawn Capital and Maturity"),
	SKIMS_AND_CUSTOMIZABLE("Skims and Customizable"),
	SKIMS_AND_MATURITY("Skims and Maturity"),
	CUSTOMIZABLE_AND_MATURITY("Customizable and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES("Interest and Repayment and Deal Fees"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL("Interest and Repayment and Undrawn Capital"),
	INTEREST_AND_REPAYMENT_AND_SKIMS("Interest and Repayment and Skims"),
	INTEREST_AND_REPAYMENT_AND_CUSTOMIZABLE("Interest and Repayment and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Interest and Deal Fees and Undrawn Capital"),
	INTEREST_AND_DEALFEES_AND_SKIMS("Interest and Deal Fees and Skims"),
	INTEREST_AND_DEALFEES_AND_CUSTOMIZABLE("Interest and Deal Fees and Customizable"),
	INTEREST_AND_DEALFEES_AND_MATURITY("Interest and Deal Fees and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Undrawn Capital and Skims"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Interest and Undrawn Capital and Customizable"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_MATURITY("Interest and Undrawn Capital and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Skims and Customizable"),
	INTEREST_AND_SKIMS_AND_MATURITY("Interest and Skims and Maturity"),
	INTEREST_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Customizable and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Repayment and Deal Fees and Undrawn Capital"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS("Repayment and Deal Fees and Skims"),
	REPAYMENT_AND_DEALFEES_AND_CUSTOMIZABLE("Repayment and Deal Fees and Customizable"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS("Repayment and Undrawn Capital and Skims"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Repayment and Undrawn Capital and Customizable"),
	REPAYMENT_AND_SKIMS_AND_CUSTOMIZABLE("Repayment and Skims and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Deal Fees and Undrawn Capital and Skims"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Deal Fees and Undrawn Capital and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_MATURITY("Deal Fees and Undrawn Capital and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE("Deal Fees and Skims and Customizable"),
	DEALFEES_AND_SKIMS_AND_MATURITY("Deal Fees and Skims and Maturity"),
	DEALFEES_AND_CUSTOMIZABLE_AND_MATURITY("Deal Fees and Customizable and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Undrawn Capital and Skims and Customizable"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Undrawn Capital and Skims and Maturity"),
	UNDRAWN_CAPITAL_AND_CUSTOMIZABLE_AND_MATURITY("Undrawn Capital and Customizable and Maturity"),
	SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Skims and Customizable and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Interest and Repayment and Deal Fees and Undrawn Capital"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS("Interest and Repayment and Deal Fees and Skims"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_CUSTOMIZABLE("Interest and Repayment and Deal Fees and Customizable"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Repayment and Undrawn Capital and Skims"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Interest and Repayment and Undrawn Capital and Customizable"),
	INTEREST_AND_REPAYMENT_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Repayment and Skims and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Deal Fees and Undrawn Capital and Skims"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Interest and Deal Fees and Undrawn Capital and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Deal Fees and Skims and Customizable"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_MATURITY("Interest and Deal Fees and Skims and Maturity"),
	INTEREST_AND_DEALFEES_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Deal Fees and Customizable and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Undrawn Capital and Skims and Customizable"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Interest and Undrawn Capital and Skims and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Undrawn Capital and Customizable and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Skims and Customizable and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Repayment and Deal Fees and Undrawn Capital and Skims"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Repayment and Deal Fees and Undrawn Capital and Customizable"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE("Repayment and Deal Fees and Skims and Customizable"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Repayment and Undrawn Capital and Skims and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Deal Fees and Undrawn Capital and Skims and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE_AND_MATURITY("Deal Fees and Undrawn Capital and Customizable and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Deal Fees and Skims and Customizable and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Undrawn Capital and Skims and Customizable and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Repayment and Deal Fees and Undrawn Capital and Skims"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE("Interest and Repayment and Deal Fees and Undrawn Capital and Customizable"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Repayment and Deal Fees and Skims and Customizable"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Repayment and Undrawn Capital and Skims and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Deal Fees and Undrawn Capital and Skims and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Customizable and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Deal Fees and Skims and Customizable and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Undrawn Capital and Skims and Customizable and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Repayment and Deal Fees and Undrawn Capital and Skims and Customizable"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Customizable and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE("Interest and Repayment and Deal Fees and Undrawn Capital and Skims and Customizable"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOMIZABLE_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Customizable and Maturity"),
	;

	private final String code;

	DateType(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
