package com.seventythreestrings.valuation.api.debtmodel.enums;

public enum DateType {
	ORIGINATION("Origination"),
	INTEREST("Interest"),
	REPAYMENT("Repayment"),
	DEALFEES("Deal Fees"),
	UNDRAWN_CAPITAL("Undrawn Capital"),
	SKIMS("Skims"),
	CUSTOM_SPECIFIC("Custom Specific"),
	CUSTOM_PRE("Custom Pre"),
	CUSTOM_EXCEL("Custom Excel"),
	MATURITY("Maturity"),
	INTEREST_AND_REPAYMENT("Interest and Repayment"),
	INTEREST_AND_DEALFEES("Interest and Deal Fees"),
	INTEREST_AND_UNDRAWN_CAPITAL("Interest and Undrawn Capital"),
	INTEREST_AND_SKIMS("Interest and Skims"),
	INTEREST_AND_CUSTOM_SPECIFIC("Interest and Custom Specific"),
	INTEREST_AND_CUSTOM_PRE("Interest and Custom Pre"),
	INTEREST_AND_CUSTOM_EXCEL("Interest and Custom Excel"),
	INTEREST_AND_MATURITY("Interest and Maturity"),
	REPAYMENT_AND_DEALFEES("Repayment and Deal Fees"),
	REPAYMENT_AND_UNDRAWN_CAPITAL("Repayment and Undrawn Capital"),
	REPAYMENT_AND_SKIMS("Repayment and Skims"),
	REPAYMENT_AND_CUSTOM_SPECIFIC("Repayment and Custom Specific"),
	REPAYMENT_AND_CUSTOM_PRE("Repayment and Custom Pre"),
	REPAYMENT_AND_CUSTOM_EXCEL("Repayment and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL("Deal Fees and Undrawn Capital"),
	DEALFEES_AND_SKIMS("Deal Fees and Skims"),
	DEALFEES_AND_CUSTOM_SPECIFIC("Deal Fees and Custom Specific"),
	DEALFEES_AND_CUSTOM_PRE("Deal Fees and Custom Pre"),
	DEALFEES_AND_CUSTOM_EXCEL("Deal Fees and Custom Excel"),
	DEALFEES_AND_MATURITY("Deal Fees and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS("Undrawn Capital and Skims"),
	UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Undrawn Capital and Custom Specific"),
	UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Undrawn Capital and Custom Pre"),
	UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Undrawn Capital and Custom Excel"),
	UNDRAWN_CAPITAL_AND_MATURITY("Undrawn Capital and Maturity"),
	SKIMS_AND_CUSTOM_SPECIFIC("Skims and Custom Specific"),
	SKIMS_AND_CUSTOM_PRE("Skims and Custom Pre"),
	SKIMS_AND_CUSTOM_EXCEL("Skims and Custom Excel"),
	SKIMS_AND_MATURITY("Skims and Maturity"),
	CUSTOM_SPECIFIC_AND_MATURITY("Custom Specific and Maturity"),
	CUSTOM_PRE_AND_MATURITY("Custom Pre and Maturity"),
	CUSTOM_EXCEL_AND_MATURITY("Custom Excel and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES("Interest and Repayment and Deal Fees"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL("Interest and Repayment and Undrawn Capital"),
	INTEREST_AND_REPAYMENT_AND_SKIMS("Interest and Repayment and Skims"),
	INTEREST_AND_REPAYMENT_AND_CUSTOM_SPECIFIC("Interest and Repayment and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_CUSTOM_PRE("Interest and Repayment and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_CUSTOM_EXCEL("Interest and Repayment and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Interest and Deal Fees and Undrawn Capital"),
	INTEREST_AND_DEALFEES_AND_SKIMS("Interest and Deal Fees and Skims"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_SPECIFIC("Interest and Deal Fees and Custom Specific"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_PRE("Interest and Deal Fees and Custom Pre"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_EXCEL("Interest and Deal Fees and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_MATURITY("Interest and Deal Fees and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Undrawn Capital and Skims"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Interest and Undrawn Capital and Custom Specific"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Interest and Undrawn Capital and Custom Pre"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Interest and Undrawn Capital and Custom Excel"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_MATURITY("Interest and Undrawn Capital and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Skims and Custom Specific"),
	INTEREST_AND_SKIMS_AND_CUSTOM_PRE("Interest and Skims and Custom Pre"),
	INTEREST_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Skims and Custom Excel"),
	INTEREST_AND_SKIMS_AND_MATURITY("Interest and Skims and Maturity"),
	INTEREST_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Custom Specific and Maturity"),
	INTEREST_AND_CUSTOM_PRE_AND_MATURITY("Interest and Custom Pre and Maturity"),
	INTEREST_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Custom Excel and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Repayment and Deal Fees and Undrawn Capital"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS("Repayment and Deal Fees and Skims"),
	REPAYMENT_AND_DEALFEES_AND_CUSTOM_SPECIFIC("Repayment and Deal Fees and Custom Specific"),
	REPAYMENT_AND_DEALFEES_AND_CUSTOM_PRE("Repayment and Deal Fees and Custom Pre"),
	REPAYMENT_AND_DEALFEES_AND_CUSTOM_EXCEL("Repayment and Deal Fees and Custom Excel"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS("Repayment and Undrawn Capital and Skims"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Repayment and Undrawn Capital and Custom Specific"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Repayment and Undrawn Capital and Custom Pre"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Repayment and Undrawn Capital and Custom Excel"),
	REPAYMENT_AND_SKIMS_AND_CUSTOM_SPECIFIC("Repayment and Skims and Custom Specific"),
	REPAYMENT_AND_SKIMS_AND_CUSTOM_PRE("Repayment and Skims and Custom Pre"),
	REPAYMENT_AND_SKIMS_AND_CUSTOM_EXCEL("Repayment and Skims and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Deal Fees and Undrawn Capital and Skims"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Deal Fees and Undrawn Capital and Custom Specific"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Deal Fees and Undrawn Capital and Custom Pre"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Deal Fees and Undrawn Capital and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_MATURITY("Deal Fees and Undrawn Capital and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC("Deal Fees and Skims and Custom Specific"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_PRE("Deal Fees and Skims and Custom Pre"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL("Deal Fees and Skims and Custom Excel"),
	DEALFEES_AND_SKIMS_AND_MATURITY("Deal Fees and Skims and Maturity"),
	DEALFEES_AND_CUSTOM_SPECIFIC_AND_MATURITY("Deal Fees and Custom Specific and Maturity"),
	DEALFEES_AND_CUSTOM_PRE_AND_MATURITY("Deal Fees and Custom Pre and Maturity"),
	DEALFEES_AND_CUSTOM_EXCEL_AND_MATURITY("Deal Fees and Custom Excel and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Undrawn Capital and Skims and Custom Specific"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Undrawn Capital and Skims and Custom Pre"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Undrawn Capital and Skims and Custom Excel"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Undrawn Capital and Skims and Maturity"),
	UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC_AND_MATURITY("Undrawn Capital and Custom Specific and Maturity"),
	UNDRAWN_CAPITAL_AND_CUSTOM_PRE_AND_MATURITY("Undrawn Capital and Custom Pre and Maturity"),
	UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL_AND_MATURITY("Undrawn Capital and Custom Excel and Maturity"),
	SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Skims and Custom Specific and Maturity"),
	SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Skims and Custom Pre and Maturity"),
	SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Skims and Custom Excel and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL("Interest and Repayment and Deal Fees and Undrawn Capital"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS("Interest and Repayment and Deal Fees and Skims"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_CUSTOM_SPECIFIC("Interest and Repayment and Deal Fees and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_CUSTOM_PRE("Interest and Repayment and Deal Fees and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_CUSTOM_EXCEL("Interest and Repayment and Deal Fees and Custom Excel"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Repayment and Undrawn Capital and Skims"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Interest and Repayment and Undrawn Capital and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Interest and Repayment and Undrawn Capital and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Interest and Repayment and Undrawn Capital and Custom Excel"),
	INTEREST_AND_REPAYMENT_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Repayment and Skims and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_SKIMS_AND_CUSTOM_PRE("Interest and Repayment and Skims and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Repayment and Skims and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Deal Fees and Undrawn Capital and Skims"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Interest and Deal Fees and Undrawn Capital and Custom Specific"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Interest and Deal Fees and Undrawn Capital and Custom Pre"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Interest and Deal Fees and Undrawn Capital and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Deal Fees and Skims and Custom Specific"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_PRE("Interest and Deal Fees and Skims and Custom Pre"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Deal Fees and Skims and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_MATURITY("Interest and Deal Fees and Skims and Maturity"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Deal Fees and Custom Specific and Maturity"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_PRE_AND_MATURITY("Interest and Deal Fees and Custom Pre and Maturity"),
	INTEREST_AND_DEALFEES_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Deal Fees and Custom Excel and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Undrawn Capital and Skims and Custom Specific"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Interest and Undrawn Capital and Skims and Custom Pre"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Undrawn Capital and Skims and Custom Excel"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Interest and Undrawn Capital and Skims and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Undrawn Capital and Custom Specific and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE_AND_MATURITY("Interest and Undrawn Capital and Custom Pre and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Undrawn Capital and Custom Excel and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Skims and Custom Specific and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Interest and Skims and Custom Pre and Maturity"),
	INTEREST_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Skims and Custom Excel and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Repayment and Deal Fees and Undrawn Capital and Skims"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Repayment and Deal Fees and Undrawn Capital and Custom Specific"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Repayment and Deal Fees and Undrawn Capital and Custom Pre"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Repayment and Deal Fees and Undrawn Capital and Custom Excel"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC("Repayment and Deal Fees and Skims and Custom Specific"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_PRE("Repayment and Deal Fees and Skims and Custom Pre"),
	REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL("Repayment and Deal Fees and Skims and Custom Excel"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Repayment and Undrawn Capital and Skims and Custom Specific"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Repayment and Undrawn Capital and Skims and Custom Pre"),
	REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Repayment and Undrawn Capital and Skims and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Deal Fees and Undrawn Capital and Skims and Custom Specific"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Deal Fees and Undrawn Capital and Skims and Custom Pre"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Deal Fees and Undrawn Capital and Skims and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC_AND_MATURITY("Deal Fees and Undrawn Capital and Custom Specific and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE_AND_MATURITY("Deal Fees and Undrawn Capital and Custom Pre and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL_AND_MATURITY("Deal Fees and Undrawn Capital and Custom Excel and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Deal Fees and Skims and Custom Specific and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Deal Fees and Skims and Custom Pre and Maturity"),
	DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Deal Fees and Skims and Custom Excel and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Undrawn Capital and Skims and Custom Specific and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Undrawn Capital and Skims and Custom Pre and Maturity"),
	UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Undrawn Capital and Skims and Custom Excel and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS("Interest and Repayment and Deal Fees and Undrawn Capital and Skims"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC("Interest and Repayment and Deal Fees and Undrawn Capital and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE("Interest and Repayment and Deal Fees and Undrawn Capital and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL("Interest and Repayment and Deal Fees and Undrawn Capital and Custom Excel"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Repayment and Deal Fees and Skims and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_PRE("Interest and Repayment and Deal Fees and Skims and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Repayment and Deal Fees and Skims and Custom Excel"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Repayment and Undrawn Capital and Skims and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Interest and Repayment and Undrawn Capital and Skims and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Repayment and Undrawn Capital and Skims and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Deal Fees and Undrawn Capital and Skims and Custom Specific"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Interest and Deal Fees and Undrawn Capital and Skims and Custom Pre"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Deal Fees and Undrawn Capital and Skims and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Custom Specific and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_PRE_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Custom Pre and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Custom Excel and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Deal Fees and Skims and Custom Specific and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Interest and Deal Fees and Skims and Custom Pre and Maturity"),
	INTEREST_AND_DEALFEES_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Deal Fees and Skims and Custom Excel and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Undrawn Capital and Skims and Custom Specific and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Interest and Undrawn Capital and Skims and Custom Pre and Maturity"),
	INTEREST_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Undrawn Capital and Skims and Custom Excel and Maturity"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Repayment and Deal Fees and Undrawn Capital and Skims and Custom Specific"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Repayment and Deal Fees and Undrawn Capital and Skims and Custom Pre"),
	REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Repayment and Deal Fees and Undrawn Capital and Skims and Custom Excel"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Custom Specific and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Custom Pre and Maturity"),
	DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Deal Fees and Undrawn Capital and Skims and Custom Excel and Maturity"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC("Interest and Repayment and Deal Fees and Undrawn Capital and Skims and Custom Specific"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE("Interest and Repayment and Deal Fees and Undrawn Capital and Skims and Custom Pre"),
	INTEREST_AND_REPAYMENT_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL("Interest and Repayment and Deal Fees and Undrawn Capital and Skims and Custom Excel"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_SPECIFIC_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Custom Specific and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_PRE_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Custom Pre and Maturity"),
	INTEREST_AND_DEALFEES_AND_UNDRAWN_CAPITAL_AND_SKIMS_AND_CUSTOM_EXCEL_AND_MATURITY("Interest and Deal Fees and Undrawn Capital and Skims and Custom Excel and Maturity"),
	;

	private final String code;

	DateType(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
