package com.seventythreestrings.valuation.api.debtmodel.dto;

public enum DateType {
	ORIGINATION,
	INTEREST,
	PREPAYMENT,
	INTEREST_AND_PREPAYMENT,
	MATURITY,
	INTEREST_AND_MATURITY,
	DEALFEES,
	DEALFEES_AND_MATURITY,
	INTEREST_UNDRAWN_CAPITAL,
	INTEREST_UNDRAWN_CAPITAL_AND_MATURITY,
	SKIMS,
	SKIMS_AND_MATURITY,
	;
}
